### ISSUE TITLE
Metallurgy Enchantment does not support anything but vanilla ores

### ISSUE THREAD

**Issue by ChubbsWasTaken** [NinjaBunny1/More-Enchantments#1]
Yeah... so i put metallurgy on a pickaxe and it only smelted vanilla ores. might i suggest checking for smelting recipes?

**Comment by NinjaBunny1** [comment]
Thank you for your suggestion!
I intentionally made it like this to reduce the number of blocks that can be smelted with metallurgy. Because of this you now have to use a data pack to edit this. For this use the tag system and the tag "forge:ores/metal". 
I will probably change it like you suggested, although only when there aren´t too big technical issues

**Comment by GreenForzeGaming** [comment]
and how do you do that... i would like to know how.

**Comment by NinjaBunny1** [comment]
https://minecraft.fandom.com/wiki/Tutorials/Creating_a_data_pack#Tags
I hope this will be helpful! And sorry for the late answer.
