### ISSUE TITLE
Compatibility with Colytra

### ISSUE THREAD

**Issue by WolfMethod** [NinjaBunny1/More-Enchantments#11]
I'm using this mod : https://www.curseforge.com/minecraft/mc-mods/colytra

It allows me to fuse the Elytra and my chestplate while retaining all enchants.

But when I did, I still saw all the Elytra enchants but when pressing the action key for either Ascending or Gust of Wind, it simply doesn't work.

Can you check and tell me if it is possible to fix ? Thanks !

I play Minecraft 1.19.2 with Forge 43.2.21

**Comment by NinjaBunny1** [comment]
Hi, thank you for your report.
I have looked into the issue and noticed, that non of the Elytra enchantments are working when fusing Elytra and chestplate.
After looking at the GitHub page of this mod I suspect that the problem is caused by the relocation of the enchantments from the Elytra to the shared item. That propably makes the More Enchantments mod unable to detect the enchantments and thereby completely passivates it.
Given enough time and a good documentation I probably could find a workaround, but at the moment I unfortunately can't due to very sparse documentation.
