### ISSUE TITLE
not working with the oreexcavation mod

### ISSUE THREAD

**Issue by GreenForzeGaming** [NinjaBunny1/More-Enchantments#3]
the vain miner in oreexcavation gets canceld and only mines 1 block when used with your enchantments 1.16.5

**Comment by NinjaBunny1** [comment]
Sorry for the late answer.
This is because of the implementation of all the Pickaxe Enchantments of my mod. To overwrite the loot they cancel the entirety of the block breaking and the break the block again. With this cancellation they simultaneously cancel OreExcavation. I am looking into a solution for this problem, but at the moment I can't see one and therefore can't provide compatibility.
