### ISSUE TITLE
Issue with 1.19.3

### ISSUE THREAD

**Issue by Furiousmoder** [NinjaBunny1/More-Enchantments#8]
whenever I open 1.19.3 forge, the mod says it isn't compatible with 1.19.3 and to switch versions to 1.19.2

**Comment by NinjaBunny1** [comment]
This is because the mod isn't compatible. I mistakenly assumed compatibility with 1.19.3 and 1.19.4 and therefore declared exactly that on the curseforge page. This will stay the same, untill I update the mod to a newer version of Minecraft Forge. I am sorry for the inconveniance as well as this late answer.

**Comment by NinjaBunny1** [comment]
Hopefully not permanently.
